"""Birch-Murnaghan equation-of-state fitting and the Lejaeghere Δ-gauge.

Pure post-processing on (volume, energy) points — no SCF dependency, so it is
trivially unit-testable. The E(V) points come from an isotropic volume scan
(see ``api.run_eos``); this module fits the 3rd-order Birch-Murnaghan form and
reports the equilibrium volume V0, bulk modulus B0, and its pressure derivative
B0'.

Base units follow the package: energy in eV, volume in Å³, so the fitted bulk
modulus is eV/Å³ internally and converted to GPa via ``EV_A3_TO_GPA``. The
Δ-value follows calcDelta 3.0 (Lejaeghere et al., Science 351, aad3000, 2016):
both curves shifted to their own minimum, RMS of the difference over
[1-w, 1+w]·V0_avg, in meV/atom.

This function set was previously copy-pasted across ``benchmarks/delta_gauge``,
``benchmarks/delta_factor`` and ``benchmarks/lejaeghere``; those now import it.
"""

from __future__ import annotations

from dataclasses import dataclass

import numpy as np

from gradwave.constants import EV_A3_TO_GPA


def birch_murnaghan(
    v: np.ndarray,
    e0: float,
    v0: float,
    b0: float,
    b0p: float,
) -> np.ndarray:
    """3rd-order Birch-Murnaghan energy-volume curve E(V).

    ``b0`` carries the same energy/volume units as ``e0``/``v`` (eV/Å³ here);
    ``b0p`` (= dB0/dP) is dimensionless. Accepts a scalar or array ``v``.
    """
    v = np.asarray(v, dtype=float)
    x = (v0 / v) ** (2.0 / 3.0)
    return e0 + 9.0 * v0 * b0 / 16.0 * (
        (x - 1.0) ** 3 * b0p + (x - 1.0) ** 2 * (6.0 - 4.0 * x))


@dataclass(frozen=True)
class BM3Fit:
    """A fitted 3rd-order Birch-Murnaghan curve. ``v0``/``e0`` inherit the
    per-atom (or per-cell) convention of the points passed to ``fit_bm3``."""

    e0: float               # eV — minimum energy
    v0: float               # Å³ — equilibrium volume
    b0: float               # eV/Å³ — bulk modulus
    b0_prime: float         # dimensionless — dB0/dP
    rms_residual_eV: float  # RMS fit residual over the input points

    @property
    def b0_GPa(self) -> float:
        return self.b0 * EV_A3_TO_GPA


def fit_bm3(volumes: np.ndarray | list[float], energies: np.ndarray | list[float]) -> BM3Fit:
    """Least-squares 3rd-order Birch-Murnaghan fit of E(V).

    Needs at least four points (the form has four parameters). The initial
    guess seeds e0/v0 from the lowest point and B0≈0.6 eV/Å³ (~100 GPa),
    B0'≈4 — the values that make ``curve_fit`` converge across the periodic
    table in the Δ-gauge benchmarks.
    """
    from scipy.optimize import curve_fit

    v = np.asarray(volumes, dtype=float)
    e = np.asarray(energies, dtype=float)
    if v.ndim != 1 or v.shape != e.shape:
        raise ValueError("volumes and energies must be matching 1-D sequences")
    if v.size < 4:
        raise ValueError(
            f"Birch-Murnaghan needs >=4 (volume, energy) points, got {v.size}")
    i = int(np.argmin(e))
    popt, _ = curve_fit(birch_murnaghan, v, e,
                        p0=[e[i], v[i], 0.6, 4.0], maxfev=40000)
    e0, v0, b0, b0p = (float(x) for x in popt)
    resid = birch_murnaghan(v, e0, v0, b0, b0p) - e
    return BM3Fit(e0=e0, v0=v0, b0=b0, b0_prime=b0p,
                  rms_residual_eV=float(np.sqrt(np.mean(resid ** 2))))


@dataclass(frozen=True)
class BM3Uncertainty:
    """Monte-Carlo (parametric bootstrap) uncertainty of a BM3 fit.

    Given a per-point energy noise sigma_e (e.g. the statistical noise floor
    from ``postscf.convergence_noise.estimate_noise_floor``), the E(V) points
    are resampled ``n_samples`` times with independent N(0, sigma_e) noise and
    refit; the reported sigmas are the sample standard deviations of the
    fitted parameters. Because fitting + differentiation are (locally) linear
    in the energies, each sigma scales linearly with sigma_e (the propagation
    the Janssen et al. 2024 protocol relies on). Units follow ``BM3Fit``:
    per-atom inputs give per-atom sigmas.
    """

    fit: BM3Fit             # the central (unperturbed) fit
    sigma_e0: float         # eV
    sigma_v0: float         # Å³
    sigma_b0: float         # eV/Å³
    sigma_b0_prime: float   # dimensionless
    n_samples: int          # bootstrap draws attempted
    n_failed: int           # draws whose fit did not converge (excluded)
    seed: int

    @property
    def sigma_b0_GPa(self) -> float:
        return self.sigma_b0 * EV_A3_TO_GPA


def bootstrap_bm3(
    volumes: np.ndarray | list[float],
    energies: np.ndarray | list[float],
    sigma_e: float | np.ndarray | list[float],
    *,
    n_samples: int = 200,
    seed: int = 0,
) -> BM3Uncertainty:
    """Propagate per-point energy noise through the BM3 fit by Monte Carlo.

    ``sigma_e`` is the 1-sigma energy noise per E(V) point (a scalar applied
    to every point, or a per-point sequence), in the same energy unit as
    ``energies``. Draws are generated by ``numpy.random.default_rng(seed)``,
    so results are reproducible; the same seed at two different sigma_e values
    reuses the same underlying standard-normal draws, making the linear
    sigma-scaling exact draw-for-draw. Fits that fail to converge on a noisy
    draw are skipped and counted in ``n_failed``; at least half the draws must
    succeed or a RuntimeError is raised.
    """
    v = np.asarray(volumes, dtype=float)
    e = np.asarray(energies, dtype=float)
    fit = fit_bm3(v, e)
    sig = np.broadcast_to(np.asarray(sigma_e, dtype=float), e.shape)
    if np.any(sig < 0.0):
        raise ValueError("sigma_e must be non-negative")
    if n_samples < 2:
        raise ValueError("need n_samples >= 2 for a standard deviation")
    rng = np.random.default_rng(seed)
    params = []
    n_failed = 0
    for _ in range(n_samples):
        noise = rng.standard_normal(e.shape) * sig
        try:
            f = fit_bm3(v, e + noise)
        except (RuntimeError, ValueError):
            n_failed += 1
            continue
        params.append((f.e0, f.v0, f.b0, f.b0_prime))
    if len(params) < max(2, n_samples // 2):
        raise RuntimeError(
            f"bootstrap failed: only {len(params)}/{n_samples} noisy BM3 fits "
            "converged — sigma_e is likely far too large for these points")
    s_e0, s_v0, s_b0, s_b0p = np.std(np.asarray(params), axis=0, ddof=1)
    return BM3Uncertainty(
        fit=fit, sigma_e0=float(s_e0), sigma_v0=float(s_v0),
        sigma_b0=float(s_b0), sigma_b0_prime=float(s_b0p),
        n_samples=n_samples, n_failed=n_failed, seed=seed)


def _as_params(
    fit: BM3Fit | tuple[float, float, float, float],
) -> tuple[float, float, float, float]:
    """Coerce a BM3Fit or a raw (e0, v0, b0, b0p) tuple to a params tuple."""
    if isinstance(fit, BM3Fit):
        return (fit.e0, fit.v0, fit.b0, fit.b0_prime)
    e0, v0, b0, b0p = fit
    return (float(e0), float(v0), float(b0), float(b0p))


def delta_value(
    fit_a: BM3Fit,
    fit_b: BM3Fit | tuple[float, float, float, float],
    window: float = 0.06,
    npoints: int = 1000,
) -> float:
    """Lejaeghere Δ (meV) between two BM3 fits.

    RMS of the energy difference over [1-window, 1+window]·V0_avg with each
    curve shifted to its own minimum. Pass per-atom fits (v0 in Å³/atom, b0 in
    eV/Å³) to get Δ in meV/atom. Accepts ``BM3Fit`` objects or raw
    (e0, v0, b0, b0p) tuples (e.g. an all-electron reference).
    """
    a = _as_params(fit_a)
    b = _as_params(fit_b)
    v0av = 0.5 * (a[1] + b[1])
    vv = np.linspace((1.0 - window) * v0av, (1.0 + window) * v0av, npoints)
    d = birch_murnaghan(vv, 0.0, *a[1:]) - birch_murnaghan(vv, 0.0, *b[1:])
    return float(np.sqrt(np.trapezoid(d ** 2, vv) / (vv[-1] - vv[0])) * 1000.0)
