#!/usr/bin/env python3
"""Regenerate src/gradwave/postscf/_d3_params.py from the DFT-D3 reference source.

Provenance: the numerical parameters are transcribed from the reference DFT-D3
implementation dftbplus/dftd3-lib (a verbatim repackaging of S. Grimme's dftd3).
They are physical reference data from Grimme, Antony, Ehrlich, Krieg, J. Chem.
Phys. 132, 154104 (2010) and the BJ-damping parametrization of Grimme, Ehrlich,
Goerigk, J. Comput. Chem. 32, 1456 (2011).

This script fetches lib/core.f90 (r2r4, rcov data blocks) and lib/pars.f90 (the
packed reference-C6 array) from the pinned upstream, replicates the copyc6/limit
unpacking, and emits the vendored module. Only the SUBSET element set below is
written (a tested subset beats an untested full table); extend SUBSET to cover
more elements, then re-run and re-run the dispersion tests.

Usage:  python scripts/gen_d3_params.py
"""
from __future__ import annotations

import re
import urllib.request
from pathlib import Path

BASE = "https://raw.githubusercontent.com/dftbplus/dftd3-lib/main/lib"
OUT = Path(__file__).resolve().parents[1] / "src/gradwave/postscf/_d3_params.py"

# Element subset to vendor: main-group organics + P/S/Cl/F and the metals Mg,
# Cu, Zn. (At least H, C, N, O plus a few metals — the task's coverage floor.)
SUBSET = [1, 6, 7, 8, 9, 12, 15, 16, 17, 29, 30]
SYM = {1: "H", 6: "C", 7: "N", 8: "O", 9: "F", 12: "Mg", 15: "P",
       16: "S", 17: "Cl", 29: "Cu", 30: "Zn"}

# D3(BJ) damping presets (s6, s8, a1, a2), a2 in Bohr — from dftd3-lib
# setfuncpar (version 4); rs6→a1, s18→s8, rs18→a2.
BJ = {
    "pbe": (1.0, 0.7875, 0.4289, 4.4407), "pbe0": (1.0, 1.2177, 0.4145, 4.8593),
    "pbesol": (1.0, 2.9491, 0.4466, 6.1742), "blyp": (1.0, 2.6996, 0.4298, 4.2359),
    "b3lyp": (1.0, 1.9889, 0.3981, 4.4211), "bp86": (1.0, 3.2822, 0.3946, 4.8516),
    "b97-d": (1.0, 2.2609, 0.5545, 3.2297), "revpbe": (1.0, 2.3550, 0.5238, 3.5016),
    "rpbe": (1.0, 0.8318, 0.1820, 4.0094), "tpss": (1.0, 1.9435, 0.4535, 4.4752),
    "tpss0": (1.0, 1.2576, 0.3768, 4.5865), "hse06": (1.0, 2.3100, 0.3830, 5.6850),
    "scan": (1.0, 0.0000, 0.5380, 5.4200),
}


def _fetch(name: str) -> str:
    with urllib.request.urlopen(f"{BASE}/{name}") as fh:
        return fh.read().decode()


def _data_block(core: str, name: str) -> list[float]:
    m = re.search(r"\n  data +%s ?/(.*?)/\n" % name, core, re.S)
    return [float(t) for t in re.findall(r"[-+]?\d*\.\d+", m.group(1).replace("&", " "))]


def _limit(iat: int, jat: int):
    iadr = jadr = 1
    while iat > 100:
        iat -= 100
        iadr += 1
    while jat > 100:
        jat -= 100
        jadr += 1
    return iat, jat, iadr, jadr


def main() -> None:
    core = _fetch("core.f90")
    pars = _fetch("pars.f90")
    r2r4 = _data_block(core, "r2r4")
    rcov = _data_block(core, "rcov")
    assert len(r2r4) == 94 and len(rcov) == 94

    vals = [float(t.replace("D", "E"))
            for t in re.findall(r"[-+]?\d*\.\d+D[-+]?\d+", pars)]
    c6ab: dict = {}
    mxc: dict = {}
    for nn in range(len(vals) // 5):
        kk = nn * 5
        c6 = vals[kk]
        iat, jat, iadr, jadr = _limit(int(round(vals[kk + 1])), int(round(vals[kk + 2])))
        cni, cnj = vals[kk + 3], vals[kk + 4]
        c6ab.setdefault((iat, jat), {})[(iadr, jadr)] = (c6, cni, cnj)
        c6ab.setdefault((jat, iat), {})[(jadr, iadr)] = (c6, cnj, cni)
        mxc[iat] = max(mxc.get(iat, 0), iadr)
        mxc[jat] = max(mxc.get(jat, 0), jadr)

    def rows(v, per=5):
        return "\n".join("    " + ", ".join(f"{x!r}" for x in v[i:i + per]) + ","
                         for i in range(0, len(v), per))

    with OUT.open("w") as f:
        f.write('"""Vendored Grimme DFT-D3 reference parameters (BJ-damping variant).\n\n')
        f.write("Generated by scripts/gen_d3_params.py from dftbplus/dftd3-lib (a verbatim\n")
        f.write("repackaging of S. Grimme's dftd3). Physical reference data from Grimme,\n")
        f.write("Antony, Ehrlich, Krieg, J. Chem. Phys. 132, 154104 (2010); BJ damping\n")
        f.write("from Grimme, Ehrlich, Goerigk, J. Comput. Chem. 32, 1456 (2011).\n\n")
        f.write("Units are atomic (Bohr, Hartree); the caller converts at the boundary.\n\n")
        f.write("R2R4[Z-1] = sqrt(0.5 * <r^4>/<r^2>_Z * sqrt(Z)) (the C8 scaling factor).\n")
        f.write("RCOV[Z-1] = covalent radius scaled by k2=4/3 and in Bohr. Both cover\n")
        f.write("Z=1..94. C6AB is CN-resolved reference C6 for the element subset\n")
        subset_syms = ", ".join(SYM[z] for z in SUBSET)
        f.write(f"{subset_syms}; each (Z_a, Z_b) maps to reference points\n")
        f.write("(i, j, C6ref, CN_a_i, CN_b_j). Extend SUBSET in the generator to add more.\n")
        f.write('"""\n\n')
        f.write("from __future__ import annotations\n\n")
        f.write("# CN counting-function steepness (exponential counting, Grimme 2010).\n")
        f.write("K1 = 16.0\n")
        f.write("# C6 CN-interpolation Gaussian width exponent (weight = exp(K3 * dCN^2)).\n")
        f.write("K3 = -4.0\n")
        f.write("# Max number of CN reference points per element in this dataset.\n")
        f.write("MAXC = 5\n\n")
        f.write("R2R4 = (\n" + rows(r2r4) + "\n)\n\n")
        f.write("RCOV = (\n" + rows(rcov) + "\n)\n\n")
        f.write("# Number of CN reference points per element (Z -> mxc).\n")
        f.write("MXC = {\n" + "".join(f"    {z}: {mxc[z]},\n" for z in SUBSET) + "}\n\n")
        f.write("# D3(BJ) damping presets per functional: (s6, s8, a1, a2). a2 in Bohr.\n")
        f.write("BJ_PARAMS = {\n")
        for k, v in BJ.items():
            f.write(f"    {k!r}: {v!r},\n")
        f.write("}\n\n")
        f.write("# (Z_a, Z_b) -> ((i, j, C6ref, CN_a_i, CN_b_j), ...)  [Hartree*Bohr^6]\n")
        f.write("C6AB = {\n")
        for a in SUBSET:
            for b in SUBSET:
                if (a, b) not in c6ab:
                    continue
                f.write(f"    ({a}, {b}): (\n")
                for (i, j), (c6, cni, cnj) in sorted(c6ab[(a, b)].items()):
                    f.write(f"        ({i}, {j}, {c6!r}, {cni!r}, {cnj!r}),\n")
                f.write("    ),\n")
        f.write("}\n")
    print(f"wrote {OUT}  ({', '.join(SYM[z] for z in SUBSET)})")


if __name__ == "__main__":
    main()
