#!/usr/bin/env python3
"""Regenerate src/gradwave/postscf/_d4_params.py from the DFT-D4 reference source.

Provenance: the numerical parameters are extracted from the reference PyTorch
port of Grimme's DFT-D4, tad-dftd4 / tad-multicharge / tad-mctc (dftd4/tad-dftd4
on GitHub, a verbatim reimplementation of the Fortran dftd4). They are physical
reference data from Caldeweyher, Bannwarth, Grimme, J. Chem. Phys. 150, 154122
(2019) and the EEQ charge model therein.

Everything below is atomic units (Bohr, Hartree); the caller converts at the
boundary. Only the SUBSET element set is written — a tested subset beats an
untested full table (same discipline as gen_d3_params.py). Extend SUBSET, then
re-run and re-run the dispersion tests.

Because the reference dynamic polarizabilities are built from *fixed* reference
charges, the pairwise reference-C6 tables (``C6REF``) are charge-independent and
are precomputed here via tad-dftd4's own Casimir–Polder machinery. The only
charge dependence left at runtime is the EEQ partial charges and the ζ scaling
of the reference weights.

Usage (needs the reference libs, not a gradwave runtime dep):
    uv run --no-project --with tad-dftd4 --with torch python scripts/gen_d4_params.py
"""
from __future__ import annotations

import math
import textwrap
from pathlib import Path

import tad_dftd4 as d4
import torch
from tad_dftd4 import data
from tad_dftd4.reference import d4 as d4ref
from tad_dftd4.reference.d4.charge_eeq import clsq
from tad_mctc.data import COV_D3, PAULING
from tad_multicharge.param import eeq2019

OUT = Path(__file__).resolve().parents[1] / "src/gradwave/postscf/_d4_params.py"

# Element subset to vendor — identical to the D3 subset (gen_d3_params.py):
# Z=1..36 (H through Kr), all of periods 1-4 main-group plus the 3d transition
# metals. tad-dftd4's reference tables carry active reference systems (nref>0)
# for every element in this range (verified: no gaps, max nref=7), so the
# boundary is a size/scope choice, not a data limit. The upstream data goes to
# Z=103; extend SUBSET if heavier elements are needed.
SUBSET = list(range(1, 37))
SYM = {
    1: "H", 2: "He", 3: "Li", 4: "Be", 5: "B", 6: "C", 7: "N", 8: "O",
    9: "F", 10: "Ne", 11: "Na", 12: "Mg", 13: "Al", 14: "Si", 15: "P",
    16: "S", 17: "Cl", 18: "Ar", 19: "K", 20: "Ca", 21: "Sc", 22: "Ti",
    23: "V", 24: "Cr", 25: "Mn", 26: "Fe", 27: "Co", 28: "Ni", 29: "Cu",
    30: "Zn", 31: "Ga", 32: "Ge", 33: "As", 34: "Se", 35: "Br", 36: "Kr",
}

# D4(BJ-EEQ-ATM) two-body damping presets (s6, s8, a1, a2). s6 is 1.0 for all;
# s9 (three-body/ATM) is out of scope for this two-body correction. From
# tad-dftd4 get_params (method d4), DOI 10.1063/1.5090222.
FUNCTIONALS = ["pbe", "pbe0", "pbesol", "blyp", "b3lyp", "bp86", "revpbe",
               "rpbe", "tpss", "tpss0", "hse06", "scan", "b97-d"]

DD = {"dtype": torch.float64}


def _fmt(x: float) -> str:
    return repr(float(x))


def _tuple(vals, indent: int = 8, width: int = 96) -> str:
    """Parenthesised float tuple; wraps onto continuation lines under ``width``."""
    items = [_fmt(v) for v in vals]
    one = "(" + ", ".join(items) + ")"
    if len(one) + indent <= width:
        return one
    pad = " " * (indent + 4)
    lines, cur = [], pad
    for it in items:
        piece = it + ", "
        if len(cur) + len(piece) > width and cur != pad:
            lines.append(cur.rstrip())
            cur = pad
        cur += piece
    lines.append(cur.rstrip())
    body = "\n".join(lines)
    return "(\n" + body + "\n" + " " * indent + ")"


def main() -> None:
    nums = torch.tensor(SUBSET)
    model = d4.D4Model(nums, **DD)
    assert float(model.ga) == 3.0 and float(model.gc) == 2.0
    wf = float(model.wf)

    # per-element scalar reference data (index by Z)
    gam = data.GAM(**DD)
    zeff = data.ZEFF(device=torch.device("cpu"))
    r4r2 = data.R4R2(**DD)
    cov = COV_D3(**DD)
    en = PAULING(**DD)

    # per-element reference blocks
    refcovcn = d4ref.refcovcn.to(torch.float64)  # (104, 7)
    refc = d4ref.refc  # (104, 7) integer counts
    refq = clsq.to(torch.float64)  # (104, 7) eeq reference charges

    nref = {z: int((refc[z] > 0).sum().item()) for z in SUBSET}

    # pairwise reference C6 (Hartree*Bohr^6): rc6[i,j] is (7,7) for the pair of
    # the i-th and j-th atoms in `nums`; trim to (nref_a, nref_b).
    rc6 = model.rc6  # (nel, nel, 7, 7)

    # BJ presets
    bj = {}
    for fn in FUNCTIONALS:
        try:
            p = d4.get_params(method="d4", functional=fn)
        except Exception:  # noqa: BLE001
            continue
        bj[fn] = (1.0, float(p["s8"]), float(p["a1"]), float(p["a2"]))

    sqrt2pi = math.sqrt(2.0 / math.pi)

    with OUT.open("w") as f:
        w = f.write
        w('"""Vendored Grimme DFT-D4 reference parameters (BJ damping, EEQ charges).\n\n')
        w("Generated by scripts/gen_d4_params.py from tad-dftd4 / tad-multicharge /\n")
        w("tad-mctc (dftd4/tad-dftd4 on GitHub), a verbatim PyTorch port of S. Grimme's\n")
        w("dftd4. Physical reference data from Caldeweyher, Bannwarth, Grimme, J. Chem.\n")
        w("Phys. 150, 154122 (2019). Units are atomic (Bohr, Hartree); the caller\n")
        w("converts at the boundary.\n\n")
        w("The pairwise reference-C6 tables C6REF are charge-independent (the reference\n")
        w("polarizabilities are built from fixed reference charges) and are precomputed\n")
        w("with tad-dftd4's Casimir-Polder integration. Runtime charge dependence enters\n")
        w("only through the EEQ partial charges and the zeta weighting of the references.\n\n")
        w("Covered subset (extend SUBSET in the generator to add more, then re-run\n")
        w("the D4 dispersion tests):\n")
        for line in textwrap.wrap(", ".join(SYM[z] for z in SUBSET) + ".", width=88):
            w(line + "\n")
        w('"""\n\n')
        w("from __future__ import annotations\n\n")

        w("# global D4 constants\n")
        w("GA = 3.0  # zeta charge-scaling height\n")
        w("GC = 2.0  # zeta charge-scaling steepness (times per-element hardness)\n")
        w(f"WF = {_fmt(wf)}  # Gaussian weight width factor for CN interpolation\n")
        w("KCN_D4 = 7.5  # steepness of the D4 covalent-CN erf counting function\n")
        w("KCN_EEQ = 7.5  # steepness of the EEQ CN erf counting function\n")
        w("CN_EEQ_MAX = 8.0  # smooth cap on the EEQ coordination number\n")
        w("D4_K4 = 4.10451  # EN-weighting prefactor in the D4 covalent CN\n")
        w("D4_K5 = 19.08857\n")
        w("D4_K6 = 254.55531485519995\n")
        w(f"SQRT_2_OVER_PI = {_fmt(sqrt2pi)}  # EEQ hardness-matrix diagonal term\n\n")

        def emit_scalar(name, tensor, comment):
            w(f"# {comment}\n{name} = {{\n")
            for z in SUBSET:
                w(f"    {z}: {_fmt(tensor[z].item())},\n")
            w("}\n\n")

        emit_scalar("GAM", gam, "chemical hardness eta_A (zeta scaling)")
        emit_scalar("ZEFF", zeff.to(torch.float64), "effective nuclear charge Z_eff (zeta scaling)")
        emit_scalar("R4R2", r4r2, "sqrt(0.5*<r^4>/<r^2>*sqrt(Z)) — C8 scaling (same as D3 Q)")
        emit_scalar("COV_D3", cov, "covalent radius [Bohr] for the CN counting functions")
        emit_scalar("EN", en, "Pauling electronegativity for the D4 CN EN-weighting")

        emit_scalar("EEQ_CHI", eeq2019.chi.to(torch.float64), "EEQ electronegativity chi")
        emit_scalar("EEQ_ETA", eeq2019.eta.to(torch.float64), "EEQ hardness eta (matrix diagonal)")
        emit_scalar("EEQ_KCN", eeq2019.kcn.to(torch.float64), "EEQ CN-scaling kappa")
        emit_scalar("EEQ_RAD", eeq2019.rad.to(torch.float64), "EEQ charge-density width alpha")

        w("# number of active reference systems per element\n")
        w("NREF = {\n")
        for z in SUBSET:
            w(f"    {z}: {nref[z]},\n")
        w("}\n\n")

        def emit_ref(name, tensor, comment, cast=float):
            w(f"# {comment}\n{name} = {{\n")
            for z in SUBSET:
                vals = [cast(tensor[z][i].item()) for i in range(nref[z])]
                if cast is int:
                    w(f"    {z}: ({', '.join(str(v) for v in vals)}),\n")
                else:
                    w(f"    {z}: {_tuple(vals)},\n")
            w("}\n\n")

        emit_ref("REF_COVCN", refcovcn, "reference covalent CN per reference system")
        emit_ref("REF_C", refc, "Gaussian-count (1 or 3) per reference system", cast=int)
        emit_ref("REF_Q", refq, "EEQ reference partial charge per reference system")

        w("# pairwise reference C6 [Hartree*Bohr^6]: (Za, Zb) -> nref_a x nref_b matrix\n")
        w("C6REF = {\n")
        for ia, za in enumerate(SUBSET):
            for ib, zb in enumerate(SUBSET):
                block = rc6[ia, ib, : nref[za], : nref[zb]]
                w(f"    ({za}, {zb}): (\n")
                for i in range(nref[za]):
                    row = [block[i, j].item() for j in range(nref[zb])]
                    w(f"        {_tuple(row)},\n")
                w("    ),\n")
        w("}\n\n")

        w("# D4(BJ) two-body damping presets per functional: (s6, s8, a1, a2). a2 in Bohr.\n")
        w("BJ_PARAMS = {\n")
        for k, v in bj.items():
            w(f"    {k!r}: {_tuple(v)},\n")
        w("}\n")

    print(f"wrote {OUT}  ({', '.join(SYM[z] for z in SUBSET)})")


if __name__ == "__main__":
    main()
