"""Unit tests for pseudo.sto_basis's fitted contracted STO radial basis
(docs/plans/cohp-contracted-basis.md's deferred step 4)."""

from __future__ import annotations

import torch

from gradwave.pseudo.sto_basis import ContractedSTO, fit_contracted_sto, n_from_label


def test_n_from_label():
    assert n_from_label("2S") == 2
    assert n_from_label("2P") == 2
    assert n_from_label("4S") == 4
    assert n_from_label("10F") == 10


def test_contracted_sto_norm_matches_definition():
    """_norm()'s closed form matches direct numerical quadrature of
    <r^(n-1)e^-zr | r^(n-1)e^-zr> with weight r^2 dr."""
    r = torch.linspace(1e-5, 30.0, 20000, dtype=torch.float64)
    rab = torch.full_like(r, float(r[1] - r[0]))
    n, l, zeta = 3, 1, 1.7
    sto = ContractedSTO(n=n, l=l, zeta=torch.tensor([zeta], dtype=torch.float64),
                        c=torch.tensor([1.0], dtype=torch.float64))
    primitive_r = r.pow(n - 1) * torch.exp(-zeta * r)
    numeric = (rab * primitive_r.pow(2) * r.pow(2)).sum()
    torch.testing.assert_close(sto._norm()[0], numeric.sqrt(), rtol=1e-3, atol=1e-6)


def test_fit_contracted_sto_synthetic_round_trip():
    """Fitting a ContractedSTO to rchi(r) generated by ANOTHER ContractedSTO
    of the same (n, l, n_primitives) recovers the target SHAPE closely (not
    necessarily the exact generating parameters -- sums of exponentials are
    a classically ill-conditioned fit, multiple (zeta, c) combinations can
    represent near-identical curves over a finite domain)."""
    torch.manual_seed(0)
    r = torch.linspace(1e-4, 6.0, 800, dtype=torch.float64)
    rab = torch.full_like(r, float(r[1] - r[0]))
    truth = ContractedSTO(n=2, l=1, zeta=torch.tensor([1.2, 2.5, 0.6], dtype=torch.float64),
                          c=torch.tensor([0.6, 0.3, 0.2], dtype=torch.float64))
    ref = truth.rchi(r)
    ref = ref / (rab * ref.pow(2)).sum().sqrt()  # unit-normalize the target

    fit, rmse = fit_contracted_sto(r, rab, ref, n=2, l=1, n_primitives=3, steps=800, lr=0.05,
                                   tail_reg=0.0)  # no compactness bias -- a pure shape round-trip
    assert rmse < 3e-3
    resid = (fit.rchi(r) - ref).abs()
    assert float(resid.max()) < 3e-2

    # the fit itself should come out unit-normalized (dr quadrature, not the
    # density-weighted fit objective)
    norm2 = (rab * fit.rchi(r).pow(2)).sum()
    assert abs(float(norm2) - 1.0) < 1e-6


def test_fit_contracted_sto_on_real_pswfc_shrinks_tail():
    """Fitting to a real UPF PP_PSWFC orbital (diamond-carbon 2P) gives a
    MORE localized radial function than the raw table -- the actual point
    of this module (docs/plans/cohp-contracted-basis.md's diffuseness gap).
    An earlier, unregularized version of this fit (plain rab-weighted L2)
    reproduced the raw table's diffuse tail almost exactly (measured: fitted
    1%-tail radius 5.05 A vs. the raw table's 5.04 A) because a UPF
    log-radial mesh's rab weight GROWS with r, rewarding an anomalously
    soft primitive that chases the tail; this guards against that
    regression."""
    from pathlib import Path

    from gradwave.pseudo.upf import parse_upf

    fix = Path(__file__).parents[1] / "fixtures" / "qe" / "pseudos"
    upf = parse_upf(fix / "PD_C_PBE_std.upf")
    o = next(o for o in upf.pswfc if o.label == "2P")
    r = torch.as_tensor(upf.r, dtype=torch.float64)
    rab = torch.as_tensor(upf.rab, dtype=torch.float64)
    rchi_ref = torch.as_tensor(o.rchi, dtype=torch.float64)

    fit, rmse = fit_contracted_sto(r, rab, rchi_ref, n=n_from_label(o.label), l=o.l,
                                   n_primitives=3, tail_reg=1e-3)
    assert rmse < 0.05  # a loose fit-quality floor, not a tight regression pin

    def tail_radius(vals: torch.Tensor, thresh: float = 0.01) -> float:
        peak = vals.abs().max()
        idx = (vals.abs() > thresh * peak).nonzero().flatten()
        return float(r[idx[-1]]) if len(idx) else 0.0

    raw_tail = tail_radius(rchi_ref)
    fit_tail = tail_radius(fit.rchi(r))
    assert fit_tail < 0.95 * raw_tail, (fit_tail, raw_tail)
